module RubyMinify
  module Pipeline
    class UnifiedRenamer
      include RenamePatcher

      def call: (ConcatenatedSource source, Array[[singleton(ConstantAliaser) | singleton(VariableRenamer) | singleton(MethodRenamer)] | [singleton(ConstantAliaser) | singleton(VariableRenamer) | singleton(MethodRenamer), Hash[Symbol, untyped]]] stage_defs) -> RenameResult
    end
  end
end
